spring:
  application:
    name: hello-client

server:
  port: 9092

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    hostname: localhost