spring:
  application:
    name: eureka-client1

server:
  port: 9091

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    hostname: localhost
    
# disable actuagor security for endpoints 
management:
  security:
    enabled: false
    
      